source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 8.0.0"
gem "sqlite3", "~> 1.7"
gem "puma", "~> 6.0"
gem "bootsnap", require: false

group :development, :test do
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
end
